services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: mystore
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - mynet
  backend:
    container_name: backend
    build:
      context: ./backend/Store
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - mynet
  frontend:
    container_name: front-end
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynet

volumes:
  postgres-data:
# nginx_log:
networks:
  mynet:
    driver: bridge
