services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: mystore
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - mynet
  backend:
    container_name: backend
    build:
      context: ./backend/Store
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=mystore;Username=postgres;Password=123456789
    ports:
      - "8081:8080"
    networks:
      - mynet

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081/api/v1
    networks:
      - mynet

volumes:
  postgres-data:
# nginx_log:
networks:
  mynet:
    driver: bridge
