services:
  backend:
    container_name: backend
    build:
      context: ./backend/Store
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  frontend:
    container_name: front-end
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"